CREATE USER comicspreviews WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

ALTER USER comicspreviews WITH PASSWORD 'comicspreviews';

CREATE DATABASE comicspreviews
    WITH 
    OWNER = comicspreviews
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;